# Generated by Django 4.1.2 on 2022-10-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locacao",
            old_name="cliente_id",
            new_name="cliente",
        ),
    ]
