# Generated by Django 4.1.2 on 2022-10-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuario", "0002_rename_cliente_id_locacao_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Filme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("ano_lancamento", models.DateField()),
                ("valor_locacao", models.IntegerField()),
                ("locacao", models.ManyToManyField(to="usuario.locacao")),
            ],
        ),
    ]
